### PR TITLE
Fix: make smoothscroll work with markdown links & update broken links (glossary)

### LINKED ISSUE #216: Clicking anchor within glossary doesn't show correctly
image

Example, click lbry-sdk from https://lbry.tech/glossary#SDK

### PR DESCRIPTION
**Pull request by Wick**
Fixes #216
Use link format ```[SPV](#spv)``` instead of ```[[SPV]]``` since same page linking is case sensitive. This link format now also enables smooth scrolling with working browser history for same page links.

### CODE REVIEW

**Comment by tzarebczan** [comment]
Thanks for the PR @Wick, we'll get a review on it!! Can we send you [some appreciation](https://LBRY.io/faq/appreciation) for your effort?

File: app/dist/scripts/app.js [hunk 1]
```diff
@@ -36,13 +36,8 @@ document.querySelectorAll("a[href^='#']").forEach(anchor => {
     if (document.getElementById(element)) {
       elementOffset = document.getElementById(element).offsetTop - 74;
       window.scroll({ top: elementOffset, behavior: "smooth" });
+      history.replaceState({}, "", `#${element}`); // Add hash to URL bar
     }
-
```
Comment (NetOperatorWibby) [inline app/dist/scripts/app.js]: Does removing this block affect other pages? For example, if I click a glossary link from the Overview page, will the smooth scroll and anchoring happen?

Comment (NetOperatorWibby) [reply app/dist/scripts/app.js]: I'm not sure how to checkout your branch to test myself.

Comment (NetOperatorWibby) [reply app/dist/scripts/app.js]: @Wick ^

Comment (Wick) [reply app/dist/scripts/app.js]: Tested on the overview page + api page and it smooth scrolls as it should and updates the URL. My reasoning behind the change was that if it manages to successfully find an element to scroll to it can safely be added to browser history.

I noticed a related issue though: that when smooth-scrolling occurs it wont get properly placed in browser history, on current site as well (navigate with the sidebar then click back in the browser).
My latest commit will fix this by changing from history.replaceState to history.pushState for updating browser history.

Let me know if you need anything more :)

Comment (NetOperatorWibby) [reply app/dist/scripts/app.js]: Sweet, sounds good to me. Thanks!
